name: Publicar carpeta cliente
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v4
      - name: Subir contenido de carpeta cliente
        uses: actions/upload-pages-artifact@v3
        with:
          path: './cliente'
      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v4
